config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks/new', to: 'tasks#new', as: :new
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  post 'tasks', to: 'tasks#create'
  get 'tasks', to: 'tasks#index', as: :index
  patch 'tasks/:id', to: 'tasks#update', as: :update
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    Task.create(task_params)

    redirect_to index_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)
    redirect_to index_path
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to index_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_controller_helper.rb
module TasksControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task, url: update_path, method: :patch) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.text_field :completed %>

  <%= f.submit %>
<% end %>
<%= link_to 'Return to list', index_path %>

app/views/tasks/index.html.erb
<h1>Tasks List</h1>

<ul>
<% @tasks.each do |task| %>
  <li>
    <input type="checkbox" name="task-list" value="" checked="<%= task[:completed] ? "checked" : "" %>">
    <%= link_to task.title, task_path(task)  %>
    <%= link_to 'Delete', delete_path(task), method: :delete, data: { confirm: "Are you sure?" } %>
  </li>
<% end %>
</ul>
<%= link_to "Add a new tak", new_path %>

app/views/tasks/new.html.erb
<%= form_for(@task, url: tasks_path, method: :post) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.text_field :completed %>

  <%= f.submit %>
<% end %>
<%= link_to 'Return to list', index_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<%= @task.details %>
<div>
  <input type="checkbox" name="task-details" value="<%= @task.completed %>">
  <% if @task.completed == false %>
  <%= "This task is not completed yet"  %>
  <% else %>
  <%= "This task is complete"  %>
  <% end %>
</div>

<br>
<br>
<%= link_to 'Edit', edit_path  %>
<br>
<br>
<%= link_to 'Return to list', index_path %>